Did basic webpack setup.
rpp32-fec-agaricus/project-atelier pull request #1
Opened 2021-12-10 05:06 UTC by PixelizedChell

@ColonelKrust @sebastianfox81 @mendelorian Let me know if this setup is good.

2021-12-10 18:33 UTC, sebastianfox81 commented
Looks good to me

2021-12-10 23:19 UTC, ColonelKrust requested changes

2021-12-10 23:19 UTC, ColonelKrust commented on .babelrc
> +  "presets": ["@babel/preset-env"]
We have two options when it comes to babel configuration when using webpack. We can configure babel withing the babelrc file and delete everything in the options object in webpack.config.js. Babel-loader will read the babelrc file and apply the configuration. We will have to add @babel/preset-react to babelrc if we choose this option. The other configuration option is to keep the options object in webpack.config.js as is and delete the babelrc file altogether. This has been referred to as the most "convenient" option, but these configurations won't be available to other tools that may need access to the babel configuration. Unless we plan to use another tool that will require access to a babelrc file (like another babel tool: babel-register, babel-node, etc), either option should work just fine.
Sources:
First answer on: https://coderedirect.com/questions/275894/whats-the-difference-when-configuring-webpack-babel-loader-vs-configuring-it-wit
This answer will tell you the two options available.
Under Webpack Loaders on: https://www.sentinelstand.com/article/create-react-app-from-scratch-with-webpack-and-babel
This is a getting started guide for creating a react app from scratch using webpack and babel. It shows and explains how babel-loader will apply the webpack configuration to babel and that a config file won't be needed.

2021-12-11 03:52 UTC, PixelizedChell commented on .babelrc
> +  "presets": ["@babel/preset-env"]
Thanks for the info. I think I'll just remove the .babelrc file.

2021-12-11 03:52 UTC, closed without merging